server:
  port: 8098
spring:
  mvc:
    static-path-pattern: /static/**
  datasource: ## todo 为配置
    url:  jdbc:mysql://localhost:3306/work_flow?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root #数据库用户
    password: mysql@password #数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 5
      max-idle: 10
      min-idle: 5
      max-wait-millis: 10000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:  # Redis 配置
    database: 1  #数据库索引(默认为0)
    host: 127.0.0.1
    port: 6379  #默认链接端口
    password: ""  #默认空的
    lettuce:
      pool:
        max-wait: -1 #最大阻赛等待时间（使用负值没有限制）默认为-1
        max-active: 8 #最大链接池
        max-idle: 8 #连接池中的最大空闲连接 默认 8
        min-idle: 0
    timeout: 5000ms
  data:
    mongodb:
      uri: mongodb://root:password@host:port/user # password 密码 @ host主机地址:post 端口/用户名
      database: test # 仓库